service: twitter

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  dailyTweet:
    handler: twitter/dailyTweet.tweet
    timeout: 45
    events:
      - schedule: 
          rate: rate(1 day)
          #enabled: false
          enabled: true

  responseTweet:
    handler: twitter/responseTweet.tweet
    timeout: 600
    events:
      - http:
          path: /response
          method: POST
  alerts:
    handler: telegram/alerts.checkDailyAlerts
    timeout: 600
    events:
      - schedule:
          #rate: cron(0 11,19 * * ? *)
          rate: rate(1 minute)
          enabled: true
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

